SELECT * FROM proyecto2.producto;
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES ("Termotanques solares", "SR-NC/NS-10", "85X1800mm; Capacidad 85l", "SUNRISE", 100, "imagen");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES ("Termotanques solares",  "SR-NC/NS-12", "85X1800mm; Capacidad 100l", "SUNRISE",10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Termotanques solares",  "SR-NC/NS-15", "85X1800mm; Capacidad 125l", "SUNRISE",10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Termotanques solares",  "SR-NC/NS-18", "85X1800mm; Capacidad 150l", "SUNRISE",10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Termotanques solares",  "SR-NC/NS-20", "85X1800mm; Capacidad 165l", "SUNRISE",10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Termotanques solares",  "SR-NC/NS-24", "85X1800mm; Capacidad 200l", "SUNRISE",10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Termotanques solares",  "SR-NC/NS-30", "85X1800mm; Capacidad 250l", "SUNRISE",10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Paneles solares",  "STM365/120-S2", "Eficiencia 20%", "SCHUTTON", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Paneles solares",  "STM370/120-S2", "Eficiencia 20.31%", "SCHUTTON", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Paneles solares",  "STM375/120-S2", "Eficiencia 20.59%", "SCHUTTON", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Paneles solares",  "STM380/120-S2", "Eficiencia 20.86%", "SCHUTTON", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Paneles solares",  "STM385/120-S2", "Eficiencia 21.13%", "SCHUTTON", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Paneles solares",  "STM390/120-S2", "Eficiencia 21.41%", "SCHUTTON", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Paneles solares",  "STM395/120-S2", "Eficiencia 21.68%", "SCHUTTON", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Controladores modulares","H220M4", "Potencia Nominal 10-40kW; Cantidad de módulos: 1-4", "DS NEW ENERGY", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Controladores modulares","H220M6", "Potencia Nominal 50-60kW; Cantidad de módulos: 5-6", "DS NEW ENERGY", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Controladores modulares","H220M8", "Potencia Nominal 70-80kW; Cantidad de módulos: 7-8", "DS NEW ENERGY", 10, "");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Baterias de Gel","8GU1", "12V, 30.5A/10H, 10.5Kg", "DOKA SOLAR", 10, "guardada");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Baterias de Gel","8G31", "12V, 90A/10H, 31.8Kg", "DOKA SOLAR", 10, "guardada");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Baterias de Gel","8G22NF", "12V, 47.5A/10H, 16.8Kg", "DOKA SOLAR", 10, "guardada");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Generadores Eólicos", "ST150", "175W, 22.5Kg, Diámetro de hélice 1500mm", "ST CHARGER", 10, "guardada");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Generadores Eólicos", "ST375", "360W, 27.5Kg, Diámetro de hélice 1600mm", "ST CHARGER", 10, "guardada");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Generadores Eólicos", "ST600", "600W, 30.5Kg, Diámetro de hélice 1800mm", "ST CHARGER", 10, "guardada");
INSERT INTO proyecto2.producto(tipo_producto, modelo, descripcion, proveedor, precio, imagen) VALUES("Generadores Eólicos", "ST1100", "1100W, 30.5Kg, Diámetro de hélice 2000mm", "ST CHARGER", 10, "guardada");
SELECT * FROM proyecto2.producto;